### ISSUE TITLE
JS Code

### ISSUE THREAD

**Issue by bernhardh** [skyrpex/gulp-less-watcher#1]
I am new to gulp, so sorry if I misunderstand something, but which languange is your example code:

import gulp        from 'gulp';
import loadPlugins from 'gulp-load-plugins';
....

Thats not JavaScript, right? How would I write this in normal js code?

**Comment by skyrpex** [comment]
It's the next JS (ES6/7). I'll assume you use gulp. If you use a file called gulpfile.babel.js instead of gulpefile.js, it'll be automatically transpiled to JS using babel. You must install babel-core before (`npm install babel-core --save`).

I'll translate the example to ES5 JS because not everyone knows about ES6/7. Regards!

``` javascript
var gulp = require('gulp');
var loadPlugins = require('gulp-load-plugins');

var $ = loadPlugins();
var config = {
  // Less config...
};

gulp.task('default', function() {
  return gulp.src('main.less', { cwd: 'resources/assets/styles/' })
    .pipe($.lessWatcher(config))
    .pipe($.sourcemaps.init())
    .pipe($.less(config))
    .pipe($.sourcemaps.write('./', { includeContent: true }))
    .pipe(gulp.dest('public/assets/'));
});
```
